### ISSUE TITLE
Error while running on colab

### ISSUE THREAD

**Issue by allthingssecurity** [abacaj/replit-3B-inference#1]
Traceback (most recent call last):
  File "/content/replit-3B-inference/ctransformers/../inference.py", line 3, in <module>
    from ctransformers import AutoModelForCausalLM, AutoConfig
ImportError: cannot import name 'AutoModelForCausalLM' from 'ctransformers' (unknown location)

**Comment by allthingssecurity** [comment]
worked for me now..

**Comment by Vinitrajputt** [comment]
> worked for me now..

can you share what commands you have used?
