### ISSUE TITLE
it should be nice to have an UI, don't you think ?

### ISSUE THREAD

**Issue by 77bgh** [abacaj/replit-3B-inference#10]
sth like this

![image](https://github.com/abacaj/replit-3B-inference/assets/64399919/08e41927-3b7f-4006-99fe-29434f4e8ad0)

and as well the possibility to index documents, and input q and receive answers from those documents

**Comment by abacaj** [comment]
Moved to discussion: https://github.com/abacaj/replit-3B-inference/discussions/12
