### ISSUE TITLE
Model type 'replit' is not supported. hmm >>> FIXED!!! 

### ISSUE THREAD

**Issue by zephirusgit** [abacaj/replit-3B-inference#5]
(replit) PS H:\ia\replit-3B-inference-main> python.exe .\inference.py
Fetching 1 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1001.74it/s]
Model type 'replit' is not supported.
Traceback (most recent call last):
  File "H:\ia\replit-3B-inference-main\inference.py", line 46, in <module>
    llm = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\ultim\miniconda3\envs\replit\lib\site-packages\ctransformers\hub.py", line 157, in from_pretrained
    return LLM(
  File "C:\Users\ultim\miniconda3\envs\replit\lib\site-packages\ctransformers\llm.py", line 214, in __init__
    raise RuntimeError(
RuntimeError: Failed to create LLM 'replit' from 'H:\ia\replit-3B-inference-main\models\replit-v2-codeinstruct-3b.q4_1.bin'.
(replit) PS H:\ia\replit-3B-inference-main>

**Comment by abacaj** [comment]
Can you share the output of command: pip list
It’s likely you didn’t use the patched ctransformers update

**Comment by Vinitrajputt** [comment]
I have pasted lines exactly as in your readme

**Comment by 77bgh** [comment]
congrats , it's pretty fast

**Comment by Vinitrajputt** [comment]
> Ok can you share the output of that command. What version of ctransformers is listed?

Model type 'replit' is not supported.
Traceback (most recent call last):
  File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\inference.py", line 46, in <module>
    llm = AutoModelForCausalLM.from_pretrained(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\env\Lib\site-packages\ctransformers\hub.py", line 157, in from_pretrained
    return LLM(
           ^^^^
  File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\env\Lib\site-packages\ctransformers\llm.py", line 214, in __init__
    raise RuntimeError(
RuntimeError: Failed to create LLM 'replit' from 'C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\models\replit-v2-codeinstruct-3b.q4_1.bin'.

Name: ctransformers
Version: 0.2.10

**Comment by abacaj** [comment]
> > Ok can you share the output of that command. What version of ctransformers is listed?
> 
> Model type 'replit' is not supported. Traceback (most recent call last): File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\inference.py", line 46, in llm = AutoModelForCausalLM.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\env\Lib\site-packages\ctransformers\hub.py", line 157, in from_pretrained return LLM( ^^^^ File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\env\Lib\site-packages\ctransformers\llm.py", line 214, in **init** raise RuntimeError( RuntimeError: Failed to create LLM 'replit' from 'C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\models\replit-v2-codeinstruct-3b.q4_1.bin'.
> 
> Name: ctransformers Version: 0.2.10

Thanks for sharing. Looks like your local is pointing to the main version of ctransformers. You'll need to use the patched version 0.2.11. For now it's included as a submodule in this repo.

Try these commands in the root directory of this project:
```sh
git submodule update --init --recursive
```

```sh
git submodule update --remote
```

**Comment by Vinitrajputt** [comment]
> > > Ok can you share the output of that command. What version of ctransformers is listed?
> > 
> > 
> > Model type 'replit' is not supported. Traceback (most recent call last): File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\inference.py", line 46, in llm = AutoModelForCausalLM.from_pretrained( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\env\Lib\site-packages\ctransformers\hub.py", line 157, in from_pretrained return LLM( ^^^^ File "C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\env\Lib\site-packages\ctransformers\llm.py", line 214, in **init** raise RuntimeError( RuntimeError: Failed to create LLM 'replit' from 'C:\Users\vinit\OneDrive\Desktop\replit-3B-inference\models\replit-v2-codeinstruct-3b.q4_1.bin'.
> > Name: ctransformers Version: 0.2.10
> 
> Thanks for sharing. Looks like your local is pointing to the main version of ctransformers. You'll need to use the patched version 0.2.11. For now it's included as a submodule in this repo.
> 
> Try these commands in the root directory of this project:
> 
> ```shell
> git submodule update --init --recursive
> ```
> 
> ```shell
> git submodule update --remote
> ```
> 
> Then install it:
> 
> ```shell
> cd ctransformers && pip install --upgrade .
> ```

Building wheels for collected packages: ctransformers
  Building wheel for ctransformers (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for ctransformers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [329 lines of output]


      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 6.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 6.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:9 (message):
        MSVC is required to pass this check.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 17 2022

        could not find any instance of Visual Studio.



      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 6.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 6.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:9 (message):
        MSVC is required to pass this check.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 16 2019 x64 v142)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 16 2019 x64 v142' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 16 2019

        could not find any instance of Visual Studio.



      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 16 2019 x64 v142' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 15 2017 x64 v141)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      -- The C compiler identification is GNU 6.3.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/MinGW/bin/gcc.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 6.3.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/MinGW/bin/c++.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:9 (message):
        MSVC is required to pass this check.


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 15 2017 x64 v141)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 15 2017 x64 v141' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Generator

          Visual Studio 15 2017

        could not find any instance of Visual Studio.



      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 15 2017 x64 v141' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         The system cannot find the file specified


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 16 2019 x64 v142)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         The system cannot find the file specified


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 16 2019 x64 v142)' generator - failure
      --------------------------------------------------------------------------------



      --------------------------------------------------------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error at CMakeLists.txt:2 (PROJECT):
        Running

         'nmake' '-?'

        failed with:

         The system cannot find the file specified


      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'NMake Makefiles (Visual Studio 15 2017 x64 v141)' generator - failure
      --------------------------------------------------------------------------------

                      ********************************************************************************
                      scikit-build could not get a working generator for your system. Aborting build.

                      Building windows wheels for Python 3.11 requires Microsoft Visual Studio 2022.
      Get it with "Visual Studio 2017":

        https://visualstudio.microsoft.com/vs/

      Or with "Visual Studio 2019":

          https://visualstudio.microsoft.com/vs/

      Or with "Visual Studio 2022":

          https://visualstudio.microsoft.com/vs/

                      ********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ctransformers
Failed to build ctransformers
ERROR: Could not build wheels for ctransformers, which is required to install pyproject.toml-based projects

do i need to install visual studio as per the error? i just did the same process as u mentioned. i am on windows 10 machine.

**Comment by abacaj** [comment]
In this case I will recommend docker, it's how I use it on my windows machine. Otherwise might need some work to adjust it

**Comment by Vinitrajputt** [comment]
> In this case I will recommend docker, it's how I use it on my windows machine. Otherwise might need some work to adjust it


Thanks for your help, I will try docker now and please provide an update in this thread so I can get to know when the next version is ready

**Comment by zephirusgit** [comment]
(replit) PS H:\ia\replit-3B-inference-main> pip list
Package            Version
------------------ --------
certifi            2023.5.7
charset-normalizer 3.1.0
colorama           0.4.6
ctransformers      0.2.10
filelock           3.12.2
fsspec             2023.6.0
huggingface-hub    0.15.1
idna               3.4
numpy              1.25.0
packaging          23.1
pip                23.1.2
PyYAML             6.0
regex              2023.6.3
requests           2.31.0
safetensors        0.3.1
setuptools         67.8.0
tokenizers         0.13.3
tqdm               4.65.0
transformers       4.30.2
typing_extensions  4.6.3
urllib3            2.0.3
wheel              0.38.4
(replit) PS H:\ia\replit-3B-inference-main>

 python --version
Python 3.9.6

i download it from web browser from git, not sure if work the git metod of install, usualy download the git in browser and install later,  i have the git from windows installed , but usually down from web browser, i can solve it follow the @77bgh 77bgh steps commented. 

i see the diferences, wen i use the pip install -n requirements.txt the command ./ctransformers <<<<<say error. i delete the line and install pip install ctransformers, 
but dont make the folder and files, that is the fail, 
transformers==4.30.2

i follow the step and now work fine, i paste all text down 
--------------SOLUTION-------------------------
(my process to install the git) and problems.
conda create -n replit python=3.9.6 pip -y        <<<to make cvenv
conda activate replit                                            <<<to enter in cvenv
pip install ctransformers
pip install -r requirements.txt                            <<<error
pip install transformers==4.30.2                     <<manual install
(i download the model whith 
python download_model.py 
try download ir from hugginface and same error)
-----------------------FIX USING GIT --------------------
(replit) PS H:\ia\replit-3B-inference-main> **git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git**  <---no
**(that is in ctransformers folder, y comence again)**

(replit) PS H:\ia\replit-3B-inference-main> git clone https://github.com/abacaj/replit-3B-inference.git

Cloning into 'replit-3B-inference'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 43 (delta 18), reused 21 (delta 5), pack-reused 0
Receiving objects: 100% (43/43), 8.94 KiB | 2.23 MiB/s, done.
Resolving deltas: 100% (18/18), done.

**make me a new folder**
**i enter here cd **
(replit) PS H:\ia\replit-3B-inference-main> cd .\replit-3B-inference\

(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference> git submodule update --init --recursive

Submodule 'ctransformers' (https://github.com/abacaj/ctransformers) registered for path 'ctransformers'
Cloning into 'H:/ia/replit-3B-inference-main/replit-3B-inference/ctransformers'...
Submodule path 'ctransformers': checked out '2e44d3416eeb376cc165b2c96b7fa0749a2b833d'
Submodule 'models/submodules/ggllm.cpp' (https://github.com/cmp-nct/ggllm.cpp) registered for path 'ctransformers/models/submodules/ggllm.cpp'
Submodule 'models/ggml' (https://github.com/ggerganov/ggml) registered for path 'ctransformers/models/submodules/ggml'
Submodule 'models/llama.cpp' (https://github.com/ggerganov/llama.cpp) registered for path 'ctransformers/models/submodules/llama.cpp'
Cloning into 'H:/ia/replit-3B-inference-main/replit-3B-inference/ctransformers/models/submodules/ggllm.cpp'...
Cloning into 'H:/ia/replit-3B-inference-main/replit-3B-inference/ctransformers/models/submodules/ggml'...
Cloning into 'H:/ia/replit-3B-inference-main/replit-3B-inference/ctransformers/models/submodules/llama.cpp'...
Submodule path 'ctransformers/models/submodules/ggllm.cpp': checked out '27b3370ea0e55519e3b9f261003c5465ec6b7d3e'
Submodule path 'ctransformers/models/submodules/ggml': checked out '4e1e135b749d2e9a2bf9abf7aa34691d1f95320d'
Submodule path 'ctransformers/models/submodules/llama.cpp': checked out 'b24c3049d96557c24782e4d32feaae65f47277af'

**(i see the command in the folder ctransformer and go here with cd)**

(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference> cd .\ctransformers\
(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers> git submodule update --init --recursive
(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers> python setup.py build
Traceback (most recent call last):
  File "H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers\setup.py", line 7, in <module>
    from skbuild import setup

**omg error but i solve VVVVVVVVVV **

ModuleNotFoundError: No module named 'skbuild'
(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers> pip install skbuild
ERROR: Could not find a version that satisfies the requirement skbuild (from versions: none)
ERROR: No matching distribution found for skbuild
(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers> dir


    Directorio: H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       28/06/2023     21:03                .github
d-----       28/06/2023     21:03                ctransformers
d-----       28/06/2023     21:03                models
d-----       28/06/2023     21:03                scripts
d-----       28/06/2023     21:03                tests
-a----       28/06/2023     21:03             43 .gitattributes
-a----       28/06/2023     21:03          13506 .gitignore
-a----       28/06/2023     21:03            333 .gitmodules
-a----       28/06/2023     21:03           4547 CMakeLists.txt
-a----       28/06/2023     21:03           1078 LICENSE
-a----       28/06/2023     21:03            150 pyproject.toml
-a----       28/06/2023     21:03          14296 README.md
-a----       28/06/2023     21:03           1797 setup.py


(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers> python.exe .\setup.py
Traceback (most recent call last):
  File "H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers\setup.py", line 7, in <module>
    from skbuild import setup
ModuleNotFoundError: No module named 'skbuild'

**omg i try other mode, usually if have setup.py i use pip install -e . and work!** 

(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers> pip install -e .
Obtaining file:///H:/ia/replit-3B-inference-main/replit-3B-inference/ctransformers
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: huggingface-hub in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from ctransformers==0.2.11) (0.15.1)
Requirement already satisfied: filelock in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub->ctransformers==0.2.11) (3.12.2)
Requirement already satisfied: fsspec in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub->ctransformers==0.2.11) (2023.6.0)
Requirement already satisfied: requests in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub->ctransformers==0.2.11) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub->ctransformers==0.2.11) (4.65.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub->ctransformers==0.2.11) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub->ctransformers==0.2.11) (4.6.3)
Requirement already satisfied: packaging>=20.9 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub->ctransformers==0.2.11) (23.1)
Requirement already satisfied: colorama in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->ctransformers==0.2.11) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from requests->huggingface-hub->ctransformers==0.2.11) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from requests->huggingface-hub->ctransformers==0.2.11) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from requests->huggingface-hub->ctransformers==0.2.11) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from requests->huggingface-hub->ctransformers==0.2.11) (2023.5.7)
Building wheels for collected packages: ctransformers
  Building editable for ctransformers (pyproject.toml) ... done
  Created wheel for ctransformers: filename=ctransformers-0.2.11-0.editable-py3-none-any.whl size=7150 sha256=a76e81f6d5b509329d961444d3490ff5bd87723f63e897a77aa29cabe9189c21
  Stored in directory: C:\Users\ultim\AppData\Local\Temp\pip-ephem-wheel-cache-ngsm9vyq\wheels\fd\fe\b2\5235633715bbcec010bc4a9d321e422a9fa2c1604e3a2b5204
Successfully built ctransformers
Installing collected packages: ctransformers
  Attempting uninstall: ctransformers
    Found existing installation: ctransformers 0.2.10
    Uninstalling ctransformers-0.2.10:
      Successfully uninstalled ctransformers-0.2.10
Successfully installed ctransformers-0.2.11

** WORK, i back to main folder with cd..**

(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference\ctransformers> cd..

** NOW WORK THE PIP INSTALL -r requeriments.txt"

(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference> pip install -r requirements.txt

Processing h:\ia\replit-3b-inference-main\replit-3b-inference\ctransformers
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: transformers==4.30.2 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from -r requirements.txt (line 2)) (4.30.2)
Requirement already satisfied: filelock in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (3.12.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (0.15.1)
Requirement already satisfied: numpy>=1.17 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (1.25.0)
Requirement already satisfied: packaging>=20.0 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (6.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (2023.6.3)
Requirement already satisfied: requests in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (0.3.1)
Requirement already satisfied: tqdm>=4.27 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from transformers==4.30.2->-r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: fsspec in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.2->-r requirements.txt (line 2)) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from huggingface-hub<1.0,>=0.14.1->transformers==4.30.2->-r requirements.txt (line 2)) (4.6.3)
Requirement already satisfied: colorama in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from tqdm>=4.27->transformers==4.30.2->-r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from requests->transformers==4.30.2->-r requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from requests->transformers==4.30.2->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from requests->transformers==4.30.2->-r requirements.txt (line 2)) (2.0.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ultim\miniconda3\envs\replit\lib\site-packages (from requests->transformers==4.30.2->-r requirements.txt (line 2)) (2023.5.7)
Building wheels for collected packages: ctransformers
  Building wheel for ctransformers (pyproject.toml) ... done
  Created wheel for ctransformers: filename=ctransformers-0.2.11-cp39-cp39-win_amd64.whl size=4562028 sha256=b4f169c631e943b8f87bee725f1eff98931584ba54feb66b6df46ecab2c3193b
  Stored in directory: C:\Users\ultim\AppData\Local\Temp\pip-ephem-wheel-cache-oyr9jtcz\wheels\fd\fe\b2\5235633715bbcec010bc4a9d321e422a9fa2c1604e3a2b5204
Successfully built ctransformers
Installing collected packages: ctransformers
  Attempting uninstall: ctransformers
    Found existing installation: ctransformers 0.2.11
    Uninstalling ctransformers-0.2.11:
      Successfully uninstalled ctransformers-0.2.11
Successfully installed ctransformers-0.2.11

**(here need the model , can use python download_model.py) i use the previus test downloader** only copy the models folder with replit-v2-codeinstruct-3b.q4_1.bin)**

**Now test and WORK :D:D:D:D:D:D:D**

(replit) PS H:\ia\replit-3B-inference-main\replit-3B-inference> python inference.py
Fetching 1 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1000.79it/s]

(and fast example prompt)
[user]: write me a sourcecode in pygame, from solar system planetary orbits, with se sun in the middle of screen and the planets from solar sistem orbiting its, in the real orden

[assistant]: import pygame
from pygame.locals import *
import sys
import math

# define constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
PLANET_RADIUS = 50
SUN_RADIUS = 50
SUN_COLOR = (255, 0, 0)
PLANET_COLOR = (0, 255, 0)

# initialize pygame
pygame.init()
screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("Solar System Orbits")

# main loop
while True:
    # update screen
    pygame.time.Clock().tick(60)

    # draw background
    screen.fill((0, 0, 0))

    # draw sun
    pygame.draw.circle(screen, SUN_COLOR, (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2), SUN_RADIUS)

    # draw planets
    for planet in range(7):
        planet_x = SCREEN_WIDTH // 2 + (planet * PLANET_RADIUS)
        planet_y = SCREEN_HEIGHT // 2
        pygame.draw.circle(screen, PLANET_COLOR, (planet_x, planet_y), PLANET_RADIUS)

    # flip the screen
    pygame.display.flip()
[user]:

**Comment by zephirusgit** [comment]
![planet](https://github.com/abacaj/replit-3B-inference/assets/20031912/40e7cd6c-bd06-4cf1-9161-68e24f7ae6d9)
and the result :D XD

**Comment by zephirusgit** [comment]
the correct step, asume u have installed git for windows. 

conda create -n replit python=3.9.6 pip -y
conda activate replit
git clone https://github.com/abacaj/replit-3B-inference.git
cd replit-3B-inference
git submodule update --init --recursive
cd ctransformers
git submodule update --init --recursive
pip install -e .
cd..
pip install -r requirements.txt
python download_model.py
python inference.py

**Comment by abacaj** [comment]
Closing this, thanks for digging in

**Comment by Vinitrajputt** [comment]
> the correct step, asume u have installed git for windows. miniconda3 python etc.
> 
> conda create -n replit python=3.9.6 pip -y conda activate replit git clone https://github.com/abacaj/replit-3B-inference.git cd replit-3B-inference git submodule update --init --recursive cd ctransformers git submodule update --init --recursive pip install -e . cd.. pip install -r requirements.txt python download_model.py python inference.py


--> pip install -r requirements.txt
this step is giving me error, is it working on your windows machine?
